"""use decimal types for receipt amounts

Revision ID: b0a4c73c3e09
Revises: 3ac4edf13d61
Create Date: 2026-09-16 15:56:14.372376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0a4c73c3e09'
down_revision: Union[str, Sequence[str], None] = '3ac4edf13d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipt_items', 'quantity',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('receipt_items', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_receipt_items_receipt_id'), 'receipt_items', ['receipt_id'], unique=False)
    op.alter_column('receipts', 'total',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_receipt_items_receipt_id'), table_name='receipt_items')
    op.alter_column('receipt_items', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('receipt_items', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
